#ifndef GRAPHICS_H
#define GRAPHICS_H

#include <Windows.h>
#include <Tchar.h>
#include <string>
#include <vector>

const int FG_BLACK      = 0;
const int FG_DARKBLUE   = FOREGROUND_BLUE;
const int FG_DARKGREEN  = FOREGROUND_GREEN;
const int FG_DARKCYAN   = FOREGROUND_BLUE   | FOREGROUND_GREEN;
const int FG_DARKRED    = FOREGROUND_RED;
const int FG_DARKMAGENTA= FOREGROUND_BLUE   | FOREGROUND_RED;
const int FG_DARKYELLOW = FOREGROUND_GREEN  | FOREGROUND_RED;
const int FG_LIGHTGREY  = FOREGROUND_BLUE   | FOREGROUND_GREEN  | FOREGROUND_RED;
const int FG_DARKGREY   = FOREGROUND_INTENSITY;
const int FG_BLUE       = FOREGROUND_BLUE   | FOREGROUND_INTENSITY;
const int FG_GREEN      = FOREGROUND_GREEN  | FOREGROUND_INTENSITY;
const int FG_CYAN       = FOREGROUND_BLUE   | FOREGROUND_GREEN  | FOREGROUND_INTENSITY;
const int FG_RED        = FOREGROUND_RED    | FOREGROUND_INTENSITY;
const int FG_MAGENTA    = FOREGROUND_BLUE   | FOREGROUND_RED    | FOREGROUND_INTENSITY;
const int FG_YELLOW     = FOREGROUND_GREEN  | FOREGROUND_RED    | FOREGROUND_INTENSITY;
const int FG_WHITE      = FOREGROUND_BLUE   | FOREGROUND_GREEN  | FOREGROUND_RED | FOREGROUND_INTENSITY;

const int BG_BLACK      = 0;
const int BG_DARKBLUE   = BACKGROUND_BLUE;
const int BG_DARKGREEN  = BACKGROUND_GREEN;
const int BG_DARKCYAN   = BACKGROUND_BLUE   | BACKGROUND_GREEN;
const int BG_DARKRED    = BACKGROUND_RED;
const int BG_DARKMAGENTA= BACKGROUND_BLUE   | BACKGROUND_RED;
const int BG_DARKYELLOW = BACKGROUND_GREEN  | BACKGROUND_RED;
const int BG_LIGHTGREY  = BACKGROUND_BLUE   | BACKGROUND_GREEN  | BACKGROUND_RED;
const int BG_DARKGREY   = BACKGROUND_INTENSITY;
const int BG_LIGHTBLUE  = BACKGROUND_BLUE   | BACKGROUND_INTENSITY;
const int BG_LIGHTGREEN = BACKGROUND_GREEN  | BACKGROUND_INTENSITY;
const int BG_CYAN       = BACKGROUND_BLUE   | BACKGROUND_GREEN  | BACKGROUND_INTENSITY;
const int BG_RED        = BACKGROUND_RED    | BACKGROUND_INTENSITY;
const int BG_MAGENTA    = BACKGROUND_BLUE   | BACKGROUND_RED    | BACKGROUND_INTENSITY;
const int BG_YELLOW     = BACKGROUND_GREEN  | BACKGROUND_RED    | BACKGROUND_INTENSITY;
const int BG_WHITE      = BACKGROUND_BLUE   | BACKGROUND_GREEN  | BACKGROUND_RED | BACKGROUND_INTENSITY;


#define UNKNOWN_GLYPH '?'
#define UNKNOWN_ID -1
#define UNKNOWN_NAME "UNKNOWN_GLYPH"
#define UNKNOWN_COLOR FG_MAGENTA


#endif